-- Aatish & Aangan - secure Supabase schema
-- Run once in a fresh Supabase project, then run seed.sql.

create extension if not exists pgcrypto;

do $$ begin
  create type public.user_role as enum ('customer', 'admin');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.order_status as enum ('Pending', 'Preparing', 'Ready');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) between 2 and 80),
  role public.user_role not null default 'customer',
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 2 and 80),
  description text not null check (char_length(trim(description)) between 10 and 280),
  price numeric(10,2) not null check (price between 50 and 100000),
  category text not null check (category in ('From the Angaar', 'Potohar Plates', 'Rice & Dum', 'Garden & Grain', 'Meetha', 'House Pour')),
  image_url text not null default 'assets/menu-atlas.webp' check (char_length(image_url) <= 500),
  image_position text not null default 'center' check (image_position in ('top-left', 'top-right', 'bottom-left', 'bottom-right', 'center')),
  badge text check (badge is null or char_length(badge) <= 30),
  spice_level smallint not null default 0 check (spice_level between 0 and 3),
  dietary text check (dietary is null or char_length(dietary) <= 40),
  available boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated always as identity unique,
  user_id uuid not null references public.profiles(id) on delete restrict,
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) between 1 and 25),
  total numeric(12,2) not null check (total > 0),
  status public.order_status not null default 'Pending',
  idempotency_key uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  preparing_at timestamptz,
  ready_at timestamptz,
  constraint orders_user_idempotency_unique unique (user_id, idempotency_key),
  constraint orders_status_timestamps_check check (
    (status = 'Pending' and preparing_at is null and ready_at is null)
    or (status = 'Preparing' and preparing_at is not null and ready_at is null)
    or (status = 'Ready' and preparing_at is not null and ready_at is not null)
  )
);

create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists orders_status_created_idx on public.orders(status, created_at desc);
create index if not exists menu_items_available_category_idx on public.menu_items(available, category);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists menu_items_touch_updated_at on public.menu_items;
create trigger menu_items_touch_updated_at
before update on public.menu_items
for each row execute function public.touch_updated_at();

drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at
before update on public.orders
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text;
begin
  v_name := trim(coalesce(new.raw_user_meta_data ->> 'full_name', ''));
  if char_length(v_name) < 2 then
    v_name := split_part(coalesce(new.email, 'Guest'), '@', 1);
  end if;
  v_name := left(v_name, 80);

  insert into public.profiles (id, full_name, role)
  values (new.id, v_name, 'customer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;

drop policy if exists profiles_read_own_or_admin on public.profiles;
create policy profiles_read_own_or_admin
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists menu_read_available_or_admin on public.menu_items;
drop policy if exists menu_authenticated_read on public.menu_items;
create policy menu_authenticated_read
on public.menu_items for select
to authenticated
using (true);

drop policy if exists menu_admin_insert on public.menu_items;
create policy menu_admin_insert
on public.menu_items for insert
to authenticated
with check (public.is_admin());

drop policy if exists menu_admin_update on public.menu_items;
create policy menu_admin_update
on public.menu_items for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists menu_admin_delete on public.menu_items;
create policy menu_admin_delete
on public.menu_items for delete
to authenticated
using (public.is_admin());

drop policy if exists orders_read_own_or_admin on public.orders;
create policy orders_read_own_or_admin
on public.orders for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

-- No client role receives INSERT or UPDATE on orders. All mutations go through
-- the validated functions below.
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.menu_items from anon, authenticated;
revoke all on table public.orders from anon, authenticated;

grant select (id, full_name, role, created_at) on public.profiles to authenticated;
grant select on public.menu_items to authenticated;
grant insert, update, delete on public.menu_items to authenticated;
grant usage, select on sequence public.menu_items_id_seq to authenticated;
grant select on public.orders to authenticated;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

create or replace function public.place_order(p_cart jsonb, p_idempotency_key uuid)
returns table (
  order_id uuid,
  order_number bigint,
  total numeric,
  status text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_raw_count integer;
  v_expected_count integer;
  v_matched_count integer;
  v_quantities_valid boolean;
  v_items jsonb;
  v_total numeric(12,2);
begin
  if v_user_id is null then
    raise exception 'Sign in before placing an order.' using errcode = '42501';
  end if;
  if p_idempotency_key is null then
    raise exception 'A checkout reference is required.' using errcode = '22023';
  end if;

  return query
  select o.id, o.order_number, o.total, o.status::text, o.created_at
  from public.orders o
  where o.user_id = v_user_id and o.idempotency_key = p_idempotency_key;
  if found then return; end if;

  if p_cart is null or jsonb_typeof(p_cart) <> 'array' then
    raise exception 'The cart format is invalid.' using errcode = '22023';
  end if;
  select count(*) into v_raw_count from jsonb_array_elements(p_cart);
  if v_raw_count < 1 or v_raw_count > 25 then
    raise exception 'Choose between 1 and 25 distinct cart lines.' using errcode = '22023';
  end if;

  with requested as (
    select item_id, sum(quantity)::integer as quantity
    from jsonb_to_recordset(p_cart) as line(item_id bigint, quantity integer)
    group by item_id
  )
  select count(*), coalesce(bool_and(item_id is not null and quantity between 1 and 20), false)
  into v_expected_count, v_quantities_valid
  from requested;

  if not v_quantities_valid then
    raise exception 'Each dish quantity must be between 1 and 20.' using errcode = '22023';
  end if;

  with requested as (
    select item_id, sum(quantity)::integer as quantity
    from jsonb_to_recordset(p_cart) as line(item_id bigint, quantity integer)
    group by item_id
  ), validated as (
    select m.id, m.name, m.price, r.quantity
    from requested r
    join public.menu_items m on m.id = r.item_id
    where m.available = true
    for share of m
  )
  select
    count(*),
    jsonb_agg(
      jsonb_build_object(
        'menu_item_id', id,
        'name', name,
        'unit_price', price,
        'quantity', quantity,
        'line_total', price * quantity
      ) order by name
    ),
    sum(price * quantity)
  into v_matched_count, v_items, v_total
  from validated;

  if v_matched_count <> v_expected_count then
    raise exception 'One or more dishes are unavailable. Refresh the menu and try again.' using errcode = '22023';
  end if;

  insert into public.orders (user_id, items, total, idempotency_key)
  values (v_user_id, v_items, v_total, p_idempotency_key);

  return query
  select o.id, o.order_number, o.total, o.status::text, o.created_at
  from public.orders o
  where o.user_id = v_user_id and o.idempotency_key = p_idempotency_key;
end;
$$;

revoke all on function public.place_order(jsonb, uuid) from public, anon;
grant execute on function public.place_order(jsonb, uuid) to authenticated;

create or replace function public.admin_update_order_status(p_order_id uuid, p_new_status text)
returns table (
  order_id uuid,
  order_number bigint,
  status text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current public.order_status;
begin
  if not public.is_admin() then
    raise exception 'Admin permission is required.' using errcode = '42501';
  end if;
  if p_new_status not in ('Pending', 'Preparing', 'Ready') then
    raise exception 'The requested order status is invalid.' using errcode = '22023';
  end if;

  select o.status into v_current
  from public.orders o
  where o.id = p_order_id
  for update;
  if not found then
    raise exception 'Order not found.' using errcode = 'P0002';
  end if;

  if v_current::text = p_new_status then
    return query select o.id, o.order_number, o.status::text, o.updated_at from public.orders o where o.id = p_order_id;
    return;
  end if;
  if not ((v_current = 'Pending' and p_new_status = 'Preparing') or (v_current = 'Preparing' and p_new_status = 'Ready')) then
    raise exception 'Orders move forward only: Pending, Preparing, then Ready.' using errcode = '22023';
  end if;

  update public.orders
  set
    status = p_new_status::public.order_status,
    preparing_at = case when p_new_status = 'Preparing' then now() else preparing_at end,
    ready_at = case when p_new_status = 'Ready' then now() else ready_at end
  where id = p_order_id;

  return query select o.id, o.order_number, o.status::text, o.updated_at from public.orders o where o.id = p_order_id;
end;
$$;

revoke all on function public.admin_update_order_status(uuid, text) from public, anon;
grant execute on function public.admin_update_order_status(uuid, text) to authenticated;

create or replace function public.get_admin_dashboard_stats()
returns table (
  total_orders_today bigint,
  total_revenue_today numeric,
  pending_orders bigint,
  total_menu_items bigint,
  unavailable_menu_items bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_day_start timestamptz;
begin
  if not public.is_admin() then
    raise exception 'Admin permission is required.' using errcode = '42501';
  end if;
  v_day_start := date_trunc('day', now() at time zone 'Asia/Karachi') at time zone 'Asia/Karachi';

  return query
  select
    count(*) filter (where o.created_at >= v_day_start),
    coalesce(sum(o.total) filter (where o.created_at >= v_day_start), 0),
    count(*) filter (where o.status = 'Pending'),
    (select count(*) from public.menu_items),
    (select count(*) from public.menu_items where available = false)
  from public.orders o;
end;
$$;

revoke all on function public.get_admin_dashboard_stats() from public, anon;
grant execute on function public.get_admin_dashboard_stats() to authenticated;

alter table public.orders replica identity full;
alter table public.menu_items replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.orders;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.menu_items;
exception when duplicate_object then null;
end $$;
